# Generated by Django 4.2.5 on 2023-09-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['price'], 'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
    ]
